# Site settings
description: Howardzhao.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. https://howardzhao.com

# User settings
username: Howardzhao.net
user_description: Memories,dreams and some little things of my life.
user_title: Howardzhao.com
email: Howard@howardzhao.com
twitter_username: zhaohao
github_username:  howardzhao
#gplus_username:  110432883173969039650
gplus_username:  101042127931315648623
disqus_username: howardzhao

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: /:title.html
#permalink: /:year-:month-:day-:title.html
highlighter: rouge
paginate: 50

#sass
sass:
    sass_dir: assets/_sass
    style: :compressed

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  startings: [html, head, body]
  profile: false

#  clippings: all
#  comments: all
#  endings: all
#  ignore:
#    envs: []
#  blanklines: true
#  profile: false
#  startings: all

# Gems
gems: [jekyll-paginate, jekyll-sitemap]
# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Archive
    url: /archive.html
  - title: About
    url: /about
  - title: Timeline
    url: /timeline.html   
#  - title: Tags
#    url: /tags
    
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
